AWSTemplateFormatVersion: '2010-09-09'
Description: A Rock Paper Scissors web stack.

Parameters:

  APIGatewayOriginDomain:
    Type: String
    Description: The domain that the API gateway is located at

  APIGatewayOriginBasePath: 
    Type: String
    Description: The basepath mapping (i.e. stage) that we want
    Default: /Prod

Resources:

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebBucket.DomainName
            Id: WebOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
          - DomainName: !Ref APIGatewayOriginDomain
            Id: ApiOrigin
            OriginPath: !Ref APIGatewayOriginBasePath
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          DefaultTTL: 0
          TargetOriginId: WebOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        Enabled: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        CacheBehaviors:
          - PathPattern: /api/*
            DefaultTTL: 0
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            ForwardedValues:
              QueryString: true

  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead


Outputs:

  WebBucketName:
    Value: !Ref WebBucket
    Description: The web bucket

  CloudFrontDistributionUrl:
    Value: !Sub https://${CDN.DomainName}
    Description: URL for the website
